/*
  Auto-generated by gltfjsx (types stripped for plain JSX).
  Draco: public/models/alien-transformed.glb — source: models/alien.glb
*/

import { useGLTF } from '@react-three/drei'

const MODEL = '/models/alien-transformed.glb'

export function AlienMesh(props) {
  const { nodes, materials } = useGLTF(MODEL)
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id5_Material_50_0.geometry}
        material={materials.Material_50}
        position={[0.036, -0.198, 0.173]}
        rotation={[0.246, -0.381, 0.093]}
        scale={0.006}
      />
    </group>
  )
}
