/*
  Auto-generated by gltfjsx (types stripped for plain JSX).
  Source: public/models/agnas1.glb → Draco-compressed to public/models/agnas1-transformed.glb
*/

import { useGLTF } from '@react-three/drei'

const MODEL = '/models/agnas1-transformed.glb'

export function ALogoMesh(props) {
  const { nodes, materials } = useGLTF(MODEL)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} scale={3.418} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} scale={3.418} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.004']} />
    </group>
  )
}

useGLTF.preload(MODEL)
