/*
  Auto-generated by gltfjsx (types stripped for plain JSX).
  Source: public/models/gargoyle.glb → Draco-compressed to public/models/gargoyle-transformed.glb
*/

import { useGLTF } from '@react-three/drei'

const MODEL = '/models/gargoyle-transformed.glb'

export function GargoyleMesh(props) {
  const { nodes, materials } = useGLTF(MODEL)
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.DevilGlobe_Model_7_u1_v1}
        rotation={[-0.029, 1.463, -3.118]}
      />
    </group>
  )
}
